version: 2
updates:
  - package-ecosystem: uv
    directory: /
    allow:
      - dependency-type: all
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      python-patch-minor:
        patterns: ["*"]
        update-types: ["patch", "minor"]
      python-major:
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: uv
    directory: /timeseries_mock
    allow:
      - dependency-type: all
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      python-patch-minor:
        patterns: ["*"]
        update-types: ["patch", "minor"]
      python-major:
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      docker-images:
        patterns: ["*"]
    ignore:
      - dependency-name: python
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns: ["*"]
